### ISSUE TITLE
Twitter API maximum amount of tweets retrieved

### ISSUE THREAD

**Issue by Myskovgaard** [abjer/sds2019#37]
Hi Everybody,

We cannot seem to find a funciton, using the twitter API, that finds the tweets between two specified dates. So far we have used:

```
id_start = 1125634881223000064
id_end = 1136190080220061698
api.user_timeline(id=name, since_id=id_start, max_id=id_end)
```
but the ```user_timeline``` will only retrieve 20 tweets, so we tried adding ```count=200```

```
id_start = 1125634881223000064
id_end = 1136190080220061698
api.user_timeline(id=name, since_id=id_start, max_id=id_end, count=200)
```
which defeats the purpose of ```since_id``` and ```max_id```, in other words:

isn't there a smarter way to get the tweets from one date to another, still using the Twitter API?

Kind regards,
Group 10

**Comment by Choptdei** [comment]
Hi. We are also using the Twitter API and we can recommend using the Sandbox Full Archive API from Twitter. You can use the Sandbox API for free and get tweets inbetween specified dates and with the freedom to add more parameters. All though it can take up to a day to get your account approved, it's still really nice. You can read more about it here: https://developer.twitter.com/en/pricing/search-fullarchive

Best regards
Group 32
